### ISSUE TITLE
do not fail when `r.keys` called on any of the types’s props, e.g. `r.keys(fooT.props)`

### ISSUE THREAD

**Issue by alexbepple** [alexbepple/kiss-and-type#24]
> TypeError: Unknown property '@@functional/placeholder'
    at Object.explodeOnUnknownProp [as get] (node_modules/kiss-and-type/dist-node/index.js:36:9)
    at _isPlaceholder (file:///…/node_modules/ramda/es/internal/_isPlaceholder.js:2:49)
    at Module.f1 (file:///…/node_modules/ramda/es/internal/_curry1.js:13:35)
    at …

**Comment by alexbepple** [comment]
https://stackoverflow.com/questions/58618168/what-s-the-meaning-of-functional-placeholder-in-ramda-source-code
https://stackoverflow.com/questions/29492333/what-does-at-at-mean-in-es6-javascript

**Comment by alexbepple** [comment]
Essentially, this is a duplicate of #2.
